name: amikhalev_hb_2025_06
channels:
  - conda-forge
  - pytorch
  - defaults
dependencies:
  # Python
  - python=3.9
  
  # Core ML/Audio dependencies (from conda for better compatibility)
  - pytorch>=2.0.0
  - torchaudio>=2.0.0
  - numpy>=1.22.0
  - pillow>=10.0.0
  - scipy>=1.9.0
  
  # System utilities
  - ffmpeg>=4.4.0
  
  # System monitoring
  - psutil>=5.9.0
  
  # Python package manager
  - pip
  
  # Development tools
  - git
  
  # Pip dependencies (packages not available in conda or need specific versions)
  - pip:
    # Telegram Bot Framework
    - aiogram==3.13.1
    
    # Environment variables
    - python-dotenv==1.0.1
    
    # Configuration
    - PyYAML==6.0.2
    
    # Speech Recognition
    - openai-whisper>=20231117
    
    # Audio/Video processing (additional to conda ffmpeg)
    - imageio-ffmpeg>=0.4.8
    
    # Local AI image generation
    - diffusers>=0.25.0
    - transformers>=4.36.0
    - accelerate>=0.25.0
    - safetensors>=0.4.0
    
    # File watching for development
    - watchdog>=3.0.0
    
    # HTTP requests for model downloads
    - aiohttp>=3.8.0
    - requests>=2.28.0
    
    # Async utilities
    - asyncio-throttle>=1.0.2
    
    # Logging enhancements
    - colorlog>=6.7.0
    
    # Development dependencies
    - pytest>=7.0.0
    - pytest-asyncio>=0.21.0
    - black>=23.0.0
    - flake8>=6.0.0
    - mypy>=1.0.0name: amikhalev_hb_2025_06
channels:
  - conda-forge
  - pytorch
  - huggingface
  - defaults
dependencies:
  # Python
  - python=3.9
  
  # Core ML/Audio dependencies (from conda for better compatibility)
  - pytorch>=2.0.0
  - torchaudio>=2.0.0
  - numpy>=1.22.0
  - pillow>=10.0.0
  - scipy>=1.9.0
  
  # System utilities
  - ffmpeg>=4.4.0
  
  # Scientific computing
  - scikit-image>=0.19.0
  
  # Python package manager
  - pip
  
  # Development tools
  - git
  
  # Pip dependencies (packages not available in conda or need specific versions)
  - pip:
    # Telegram Bot Framework
    - aiogram==3.13.1
    
    # Environment variables
    - python-dotenv==1.0.1
    
    # Configuration
    - PyYAML==6.0.2
    
    # Speech Recognition
    - openai-whisper>=20231117
    
    # Audio/Video processing (additional to conda ffmpeg)
    - imageio-ffmpeg>=0.4.8
    
    # Hugging Face ecosystem for AI image generation
    - huggingface-hub>=0.19.0
    - diffusers>=0.25.0
    - transformers>=4.36.0
    - accelerate>=0.25.0
    
    # File watching for development
    - watchdog>=3.0.0
    
    # HTTP requests for API calls
    - aiohttp>=3.8.0
    - requests>=2.28.0
    
    # Async utilities
    - asyncio-throttle>=1.0.2
    
    # Logging enhancements
    - colorlog>=6.7.0
    
    # Development dependencies
    - pytest>=7.0.0
    - pytest-asyncio>=0.21.0
    - black>=23.0.0
    - flake8>=6.0.0
    - mypy>=1.0.0
    