# Birthday Bot - Основная конфигурация
# Этот файл содержит все параметры проекта кроме токенов и секретов
# Токены должны быть указаны в отдельном файле secrets.yaml

# =============================================================================
# НАСТРОЙКИ ЛОКАЛЬНОЙ ГЕНЕРАЦИИ ИЗОБРАЖЕНИЙ
# =============================================================================
diffusion:
  # Модель для генерации изображений
  # Для FLUX используйте: "black-forest-labs/FLUX.1-dev" или "black-forest-labs/FLUX.1-schnell"
  # Для Stable Diffusion: "stabilityai/stable-diffusion-xl-base-1.0"
  # model: "black-forest-labs/FLUX.1-dev"
  model: "black-forest-labs/FLUX.1-schnell"
  
  # Устройство для генерации: auto, cpu, cuda, mps
  # auto - автоматическое определение всех доступных GPU
  device: "auto"
  
  # Список GPU устройств для multi-GPU генерации
  # Если пустой - будет автоматически определен при device: "auto"
  # Примеры:
  # gpu_devices: ["cuda:0", "cuda:1", "cuda:2"]  # 3 GPU
  # gpu_devices: ["cuda:0"]                      # 1 GPU
  # gpu_devices: ["cpu"]                         # только CPU
  gpu_devices: []
  
  # Максимальный размер очереди ожидания генерации
  # Если все GPU заняты, пользователи ждут в очереди
  max_queue_size: 10
  
  # Размер генерируемых изображений
  width: 1024
  height: 1024
  
  # Количество шагов генерации
  # FLUX.1-dev: 20-30 шагов (рекомендуется 20)
  # FLUX.1-schnell: 4 шага
  # Stable Diffusion: 20-50 шагов
  num_inference_steps: 4
  
  # Сила следования промпту
  # FLUX: 3.5-4.0 (меньше чем для SD)
  # Stable Diffusion: 7.5
  guidance_scale: 3.5
  
  # Seed для воспроизводимости (-1 для случайного)
  seed: -1
  
  # Негативный промпт (FLUX лучше понимает естественный язык)
  negative_prompt: "low quality, blurry, distorted, ugly, dark"
  
  # Предзагрузка модели при старте (true/false)
  # true - быстрее первая генерация, но дольше запуск
  # false - быстрее запуск, но медленнее первая генерация
  preload_model: true
  
  # Оптимизации для GPU
  enable_xformers: false
  enable_cpu_offload: false

  # Количество генерируемых изображений
  num_images: 4

  # Настройки промптов для генерации
  prompts:
    # Базовый промпт для всех изображений
    # base_picture: "fun, joyful, happy"
    base_picture: ""
    
    # Стилистические указания
    style: "joyful cartoon picture"
    
    # Описание главного персонажа
    # subject: "young beautiful woman named Evelina, dark long hair, big eyes"
    subject: "Evelin is a young beautiful woman, dark long hair, big eyes"
    
    # Шаблон полного промпта
    # Используются плейсхолдеры: {picture}, {style}, {subject}, {content}
    # template_with_style: "<picture>{picture}</picture>, <style>{style}</style>, <subject>{subject}</subject>, <content>{content}</content>"
    # template_no_style: "<picture>{picture}</picture>, <subject>{subject}</subject>, <content>{content}</content>"
    template_with_style: "{picture}. {style}. {content}. {subject}"
    template_no_style: "{picture}. {content}. {subject}"

# =============================================================================
# НАСТРОЙКИ РАСПОЗНАВАНИЯ РЕЧИ
# =============================================================================
speech:
  # Модель OpenAI Whisper
  # Доступные: tiny, base, small, medium, large
  # Рекомендации:
  # - tiny: самая быстрая, низкое качество (~39MB)
  # - base: быстрая, приемлемое качество (~74MB)
  # - small: сбалансированная (рекомендуется) (~244MB)
  # - medium: медленная, высокое качество (~769MB)
  # - large: самая медленная, лучшее качество (~1550MB)
  model_name: "small"
  
  # Устройство для Whisper (cpu, cuda, или auto)
  # auto - автоматическое определение всех доступных GPU для речи
  device: "auto"
  
  # Список GPU устройств для multi-GPU распознавания речи
  # Если пустой - будет автоматически определен при device: "auto"
  # Примеры:
  # gpu_devices: ["cuda:0", "cuda:1"]  # 2 GPU для речи
  # gpu_devices: ["cuda:0"]            # 1 GPU для речи
  # gpu_devices: ["cpu"]               # только CPU
  gpu_devices: []
  
  # Язык для распознавания речи
  language: "ru"
  
  # Максимальная длительность аудио в секундах
  max_audio_duration: 60
  
  # Поддерживаемые форматы аудиофайлов
  supported_formats:
    - ".ogg"
    - ".mp3"
    - ".wav"
    - ".m4a"
    - ".flac"
  
  # Директория для временных аудиофайлов
  temp_audio_dir: "temp/audio"

# =============================================================================
# НАСТРОЙКИ БЕЗОПАСНОСТИ И ЛИМИТОВ
# =============================================================================
security:
  # Максимальная длительность голосовых сообщений (секунды)
  max_voice_duration: 60
  
  # Лимит сообщений в минуту на пользователя
  rate_limit_messages: 10

# Настройки файловой системы
file:
  # Максимальный размер загружаемых файлов (20MB)
  max_file_size: 20971520
  
  # Максимальный возраст временных файлов (24 часа)
  max_temp_file_age: 86400

# =============================================================================
# ПУТИ К ФАЙЛАМ И ДИРЕКТОРИЯМ
# =============================================================================
paths:
  # Основная директория для временных файлов
  temp_dir: "temp"
  
  # Поддиректории для разных типов файлов
  temp_audio: "temp/audio"
  temp_images: "temp/images"
  
  # Директория для логов
  logs_dir: "logs"

# =============================================================================
# НАСТРОЙКИ ЛОГИРОВАНИЯ
# =============================================================================
logging:
  # Уровень логирования: DEBUG, INFO, WARNING, ERROR, CRITICAL
  # Для разработки: DEBUG, для продакшена: INFO
  level: "INFO"
  
  # Формат сообщений лога
  format: "%(asctime)s [%(name)s](%(levelname)s) %(filename)s:%(lineno)d: %(message)s"
  
  # Максимальный размер файла лога (10MB)
  max_bytes: 10485760
  
  # Количество архивных файлов логов
  backup_count: 5

# =============================================================================
# ДОПОЛНИТЕЛЬНЫЕ НАСТРОЙКИ
# =============================================================================

# Настройки для разработки
development:
  # Автоматический перезапуск при изменении файлов
  auto_reload: true
  
  # Детальное логирование в консоль
  verbose_console: true
  
  # Сохранение отладочных изображений
  save_debug_images: false

# Настройки для продакшена
production:
  # Оптимизации для продакшена
  optimize_memory: true
  
  # Очистка временных файлов при старте
  cleanup_on_start: true
  
  # Мониторинг производительности
  performance_monitoring: true
  