# Birthday Bot - Основная конфигурация
# Этот файл содержит все параметры проекта кроме токенов и секретов
# Токены должны быть указаны в отдельном файле secrets.yaml

# =============================================================================
# НАСТРОЙКИ ЛОКАЛЬНОЙ ГЕНЕРАЦИИ ИЗОБРАЖЕНИЙ
# =============================================================================


diffusion:
  # FLUX.1-dev - самая современная модель
  model: "black-forest-labs/FLUX.1-dev"
  
  # Оптимальные настройки для FLUX
  device: "auto"
  width: 1024
  height: 1024
  num_inference_steps: 20      # FLUX работает хорошо с 15-25 шагами
  guidance_scale: 3.5          # Для FLUX обычно 2.5-4.0
  seed: -1
  
  # FLUX понимает более естественные негативные промпты
  negative_prompt: "low quality, blurry, distorted, amateur photography"
  
  # Для FLUX рекомендуется
  preload_model: false
  enable_xformers: true
  enable_cpu_offload: true

# diffusion:
#   # Модель для генерации изображений (Stable Diffusion)
#   # Рекомендуемые модели:
#   # - stabilityai/stable-diffusion-xl-base-1.0 (лучшее качество, ~6GB)
#   # - runwayml/stable-diffusion-v1-5 (компактнее, ~4GB)
#   # - stabilityai/stable-diffusion-2-1 (хорошее качество, ~5GB)
#   model: "stabilityai/stable-diffusion-xl-base-1.0"
#   # Для художественного стиля
#   # model: "dreamlike-art/dreamlike-diffusion-1.0"

#   # Устройство для генерации: auto, cpu, cuda, mps
#   # auto - автоматический выбор (рекомендуется)
#   # cuda - для NVIDIA GPU
#   # mps - для Apple Silicon (M1/M2)
#   # cpu - для CPU (медленно)
#   device: "auto"
  
#   # Размер генерируемых изображений
#   width: 1024
#   height: 1024
  
#   # Количество шагов генерации (больше = лучше качество, но медленнее)
#   # Рекомендуется: 20-50 для быстрой генерации, 50-100 для качества
#   num_inference_steps: 28
  
#   # Сила следования промпту (7.5 - стандарт)
#   # Меньше = больше креативности, больше = точнее следует описанию
#   guidance_scale: 7.5
  
#   # Seed для воспроизводимости (-1 для случайного)
#   seed: -1
  
#   # Негативный промпт (что НЕ должно быть на изображении)
#   negative_prompt: "blurry, low quality, distorted, deformed, ugly, bad anatomy, watermark, signature, text, letters"
  
#   # Предзагрузка модели при старте (true/false)
#   # true - быстрее первая генерация, но дольше запуск
#   # false - быстрее запуск, но медленнее первая генерация
#   preload_model: false
  
#   # Оптимизации для GPU
#   enable_xformers: true
#   enable_cpu_offload: true

# =============================================================================
# НАСТРОЙКИ РАСПОЗНАВАНИЯ РЕЧИ
# =============================================================================
speech:
  # Модель OpenAI Whisper
  # Доступные: tiny, base, small, medium, large
  # Рекомендации:
  # - tiny: самая быстрая, низкое качество (~39MB)
  # - base: быстрая, приемлемое качество (~74MB)
  # - small: сбалансированная (рекомендуется) (~244MB)
  # - medium: медленная, высокое качество (~769MB)
  # - large: самая медленная, лучшее качество (~1550MB)
  model_name: "small"
  
  # Устройство для Whisper (cpu или cuda)
  # Используйте cuda только если у вас есть совместимая видеокарта NVIDIA
  device: "cpu"
  
  # Язык для распознавания речи
  language: "ru"
  
  # Максимальная длительность аудио в секундах
  max_audio_duration: 60
  
  # Поддерживаемые форматы аудиофайлов
  supported_formats:
    - ".ogg"
    - ".mp3"
    - ".wav"
    - ".m4a"
    - ".flac"
  
  # Директория для временных аудиофайлов
  temp_audio_dir: "temp/audio"

# =============================================================================
# НАСТРОЙКИ БЕЗОПАСНОСТИ И ЛИМИТОВ
# =============================================================================
security:
  # Максимальная длительность голосовых сообщений (секунды)
  max_voice_duration: 60
  
  # Лимит сообщений в минуту на пользователя
  rate_limit_messages: 10

# Настройки файловой системы
file:
  # Максимальный размер загружаемых файлов (20MB)
  max_file_size: 20971520
  
  # Максимальный возраст временных файлов (24 часа)
  max_temp_file_age: 86400

# =============================================================================
# ПУТИ К ФАЙЛАМ И ДИРЕКТОРИЯМ
# =============================================================================
paths:
  # Основная директория для временных файлов
  temp_dir: "temp"
  
  # Поддиректории для разных типов файлов
  temp_audio: "temp/audio"
  temp_images: "temp/images"
  
  # Директория для логов
  logs_dir: "logs"

# =============================================================================
# НАСТРОЙКИ ЛОГИРОВАНИЯ
# =============================================================================
logging:
  # Уровень логирования: DEBUG, INFO, WARNING, ERROR, CRITICAL
  # Для разработки: DEBUG, для продакшена: INFO
  level: "INFO"
  
  # Формат сообщений лога
  format: "%(asctime)s [%(name)s](%(levelname)s) %(filename)s:%(lineno)d: %(message)s"
  
  # Максимальный размер файла лога (10MB)
  max_bytes: 10485760
  
  # Количество архивных файлов логов
  backup_count: 5

# =============================================================================
# ДОПОЛНИТЕЛЬНЫЕ НАСТРОЙКИ
# =============================================================================

# Настройки для разработки
development:
  # Автоматический перезапуск при изменении файлов
  auto_reload: true
  
  # Детальное логирование в консоль
  verbose_console: true
  
  # Сохранение отладочных изображений
  save_debug_images: false

# Настройки для продакшена
production:
  # Оптимизации для продакшена
  optimize_memory: true
  
  # Очистка временных файлов при старте
  cleanup_on_start: true
  
  # Мониторинг производительности
  performance_monitoring: true
